name: tests

on:
  push:
    branches: [ main ]
  pull_request:


permissions:
  contents: write
name: Run Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      run: pytest

    - name: Generate coverage badge
      run: coverage-badge -o coverage.svg -f

    - name: Commit coverage badge
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add coverage.svg
        git commit -m "chore(ci): update coverage badge" || echo "No changes to commit"
        git push

!coverage.svg
